//! Dashboard-owned read-only trajectory store.
//!
//! `ReadOnlyStore` owns its turso connection PRIVATELY and exposes only
//! typed SELECT methods — no `execute`, no raw-SQL-accepting method, no
//! connection accessor escapes this module. It writes its own SELECTs
//! against the `trajectory_events` schema and deserializes rows into
//! harness event types; the harness's write-capable store API is never
//! imported in `src/` (the schema coupling is pinned by
//! `tests/schema_contract.rs`).
//!
//! All reads go through a dashboard-private snapshot copy (see
//! [`super::snapshot`]); a missing live DB serves empty results and is
//! never created.

use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use tokio::sync::RwLock;
use tracing::{debug, warn};

use super::snapshot::{copy_live_db, open_snapshot, wal_path};

/// Readability state of the trajectory database, as observed through the
/// snapshot-copy path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DbState {
    /// The live db file does not exist — an empty system, not an error.
    Absent,
    /// The snapshot copy opened and a SELECT succeeded.
    Readable,
    /// The live file exists but a fresh snapshot could not be opened or
    /// queried (refresh failed twice — torn-copy window persisted).
    Unavailable,
}

/// Store-level health report consumed by the `/health` route.
#[derive(Debug, Clone)]
pub struct StoreHealth {
    pub db_state: DbState,
    /// Total event rows visible through the snapshot copy.
    pub event_count: Option<u64>,
    /// Seconds since the current snapshot copy was taken.
    pub snapshot_age_seconds: Option<u64>,
}

/// The live-file stat a snapshot was taken from. The WAL sidecar is folded
/// in (max mtime, summed length): turso appends committed frames to the
/// `-wal` file without touching the main db file, so stat-gating on the db
/// file alone would miss every write between checkpoints.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct SourceStat {
    mtime: SystemTime,
    len: u64,
}

fn stat_source(live: &Path) -> std::io::Result<SourceStat> {
    let db_meta = std::fs::metadata(live)?;
    let mut mtime = db_meta.modified()?;
    let mut len = db_meta.len();
    if let Ok(wal_meta) = std::fs::metadata(wal_path(live)) {
        if let Ok(wal_mtime) = wal_meta.modified() {
            mtime = mtime.max(wal_mtime);
        }
        len += wal_meta.len();
    }
    Ok(SourceStat { mtime, len })
}

/// Raw output row of the aggregate SELECT: one row per trajectory with
/// event counts and the first/last activity timestamps as the stored
/// RFC 3339 TEXT (`+00:00` form — callers parse with chrono).
#[derive(Debug, Clone)]
pub struct AggregateRow {
    pub trajectory_id: String,
    pub event_count: u64,
    /// `MIN(timestamp)` — stored RFC 3339 TEXT.
    pub first_event_at: String,
    /// `MAX(timestamp)` — the "last activity" sort key, RFC 3339 TEXT.
    pub last_activity: String,
    pub agent_id: String,
    pub agent_provider: String,
    pub action_count: u64,
    pub observation_count: u64,
    pub control_count: u64,
    pub state_count: u64,
}

/// One Control-category row for the page-scoped status/count fold:
/// `event_type` is the harness writer's string (`Started`/`Completed`/…/
/// `Adjudicated`), `actor_id` discriminates cedar vs monitor records.
#[derive(Debug, Clone)]
pub struct ControlRow {
    pub trajectory_id: String,
    pub event_type: String,
    pub event_json: String,
    pub actor_id: String,
}

/// One Adjudicated row for the Rust post-filter phase: `event_json`
/// carries the typed `Adjudicated` payload, `raw_json` the sibling
/// `{request, response, monitor}` structure (label source).
#[derive(Debug, Clone)]
pub struct AdjudicatedRow {
    pub trajectory_id: String,
    pub event_json: String,
    pub raw_json: Option<String>,
    pub actor_id: String,
}

/// Generated positional-placeholder list `?{start+1},…,?{start+count}` for
/// dynamic IN clauses — placeholders are generated by count and values are
/// always bound, never interpolated.
fn placeholder_list(start: usize, count: usize) -> String {
    (start + 1..=start + count)
        .map(|i| format!("?{i}"))
        .collect::<Vec<_>>()
        .join(",")
}

/// One opened snapshot copy plus the live-file stat it was taken from.
struct Snapshot {
    _db: turso::Database,
    conn: turso::Connection,
    src_mtime: SystemTime,
    src_len: u64,
    copied_at: SystemTime,
    /// This snapshot's copy file (the `-wal` sidecar derives via
    /// [`wal_path`]) — owned so Drop can delete the pair.
    copy_db: PathBuf,
}

impl Snapshot {
    fn is_fresh(&self, stat: &SourceStat) -> bool {
        self.src_mtime == stat.mtime && self.src_len == stat.len
    }

    fn age_seconds(&self) -> Option<u64> {
        self.copied_at.elapsed().ok().map(|d| d.as_secs())
    }
}

/// Deleting the copy pair on Drop bounds the copy-dir footprint at one
/// pair — an unbounded leak onto the volume shared with the live
/// `trajectories.db` would eventually break harness writes, the exact
/// hot-path side effect snapshot isolation exists to prevent. The
/// `*guard = Some(snapshot)` replacement in `refresh` drops the old
/// snapshot, and the absent-DB `*guard = None` path gets the same cleanup
/// for free. Unlinking while the turso connection still holds the fd is
/// safe on both supported Unix targets (linux-gnu, apple-darwin) — the fd
/// stays valid until the connection itself drops. Best-effort: both
/// removals are discarded, Drop never panics.
impl Drop for Snapshot {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.copy_db);
        let _ = std::fs::remove_file(wal_path(&self.copy_db));
    }
}

/// Read-only view over the harness's trajectory database.
///
/// Public surface (the ONLY methods that escape the storage module):
/// [`Self::new`], [`Self::with_refresh_debounce`],
/// [`Self::health`], [`Self::count_events`],
/// [`Self::events_for_trajectory`], [`Self::force_refresh`],
/// [`Self::snapshot_taken_at`], [`Self::trajectory_aggregates`],
/// [`Self::control_rows`], [`Self::adjudicated_rows`],
/// [`Self::trajectory_ids_in_range`], [`Self::max_event_row_id`],
/// [`Self::events_after_id`].
pub struct ReadOnlyStore {
    live_db_path: PathBuf,
    copy_dir: PathBuf,
    /// Minimum interval between snapshot re-copies. A changed live file
    /// inside this window serves the existing snapshot instead of
    /// re-copying; [`Self::force_refresh`] bypasses it.
    refresh_debounce: Duration,
    /// `None` until the first successful copy, and cleared again whenever
    /// the live file goes missing (serve empty).
    inner: RwLock<Option<Snapshot>>,
}

/// Default re-copy debounce: at most one snapshot copy per second under
/// read pressure.
const MIN_REFRESH_INTERVAL: Duration = Duration::from_secs(1);

impl ReadOnlyStore {
    /// Construct the store. Performs NO I/O on the live path — the first
    /// stat/copy happens lazily on first read (a missing DB must never be
    /// created, and constructing the store must not touch it).
    pub fn new(live_db_path: PathBuf, copy_dir: PathBuf) -> Self {
        Self {
            live_db_path,
            copy_dir,
            refresh_debounce: MIN_REFRESH_INTERVAL,
            inner: RwLock::new(None),
        }
    }

    /// Override the re-copy debounce (codebase `with_x` convention: set one
    /// field, return `Self`). Tests use `Duration::ZERO` to keep proving
    /// raw stat-on-access refresh.
    pub fn with_refresh_debounce(mut self, refresh_debounce: Duration) -> Self {
        self.refresh_debounce = refresh_debounce;
        self
    }

    /// Force a snapshot refresh, bypassing ONLY the debounce (the detail
    /// routes' retry-on-miss path). The `(mtime, len)` freshness check still
    /// short-circuits an unchanged live file, which bounds the unknown-id
    /// DoS surface.
    pub async fn force_refresh(&self) -> Result<()> {
        self.refresh(true).await
    }

    /// RFC 3339-convertible time the current snapshot copy was taken (feeds
    /// the `X-Sondera-Snapshot-At` response header). `None` before any
    /// successful copy or for an absent live DB. Never triggers a refresh —
    /// handlers call it AFTER their query.
    pub async fn snapshot_taken_at(&self) -> Option<DateTime<Utc>> {
        let guard = self.inner.read().await;
        guard
            .as_ref()
            .map(|snapshot| DateTime::<Utc>::from(snapshot.copied_at))
    }

    /// Copy the live db + wal and open the copy. On open failure the torn
    /// copy files are deleted so a retry starts from a fresh copy.
    async fn try_snapshot(&self, stat: SourceStat) -> Result<Snapshot> {
        let copy = copy_live_db(&self.live_db_path, &self.copy_dir)?;
        let copy_db = copy.as_path().to_path_buf();
        match open_snapshot(copy).await {
            Ok((db, conn)) => Ok(Snapshot {
                _db: db,
                conn,
                src_mtime: stat.mtime,
                src_len: stat.len,
                copied_at: SystemTime::now(),
                copy_db: copy_db.clone(),
            }),
            Err(e) => {
                let _ = std::fs::remove_file(&copy_db);
                let _ = std::fs::remove_file(wal_path(&copy_db));
                Err(e)
            }
        }
    }

    /// Stat-on-access staleness gate.
    ///
    /// - Live file missing: clear the snapshot and serve empty (the file is
    ///   NEVER created).
    /// - Live (mtime, len) unchanged vs the current snapshot: keep it.
    /// - Changed, but the current snapshot is younger than the debounce and
    ///   `bypass_debounce` is false: serve the existing snapshot without
    ///   re-copying. The debounce never blocks the FIRST copy (no snapshot
    ///   -> always copy), and [`Self::force_refresh`] bypasses it.
    /// - Otherwise copy + open; on open error delete the copy and retry
    ///   ONCE (the harness may have committed mid-copy — a torn tail). On
    ///   second failure keep the old snapshot, if any, and surface
    ///   `Unavailable` through [`Self::health`].
    async fn refresh(&self, bypass_debounce: bool) -> Result<()> {
        let stat = match stat_source(&self.live_db_path) {
            Ok(stat) => stat,
            Err(_) => {
                let mut guard = self.inner.write().await;
                *guard = None;
                return Ok(());
            }
        };

        {
            let guard = self.inner.read().await;
            if guard.as_ref().is_some_and(|s| s.is_fresh(&stat)) {
                return Ok(());
            }
        }

        let mut guard = self.inner.write().await;
        // Re-check under the write lock: another task may have refreshed.
        if guard.as_ref().is_some_and(|s| s.is_fresh(&stat)) {
            return Ok(());
        }

        // Debounce: the stat shows change but a recent snapshot exists —
        // serve it instead of re-copying.
        if !bypass_debounce
            && guard.as_ref().is_some_and(|s| {
                s.copied_at
                    .elapsed()
                    .is_ok_and(|age| age < self.refresh_debounce)
            })
        {
            return Ok(());
        }

        let snapshot = match self.try_snapshot(stat).await {
            Ok(snapshot) => snapshot,
            Err(first_err) => {
                warn!(error = %first_err, "snapshot open failed; retrying once (torn-copy window)");
                self.try_snapshot(stat)
                    .await
                    .context("snapshot copy failed twice")?
            }
        };
        *guard = Some(snapshot);
        debug!("snapshot refreshed");
        Ok(())
    }

    /// Debounce-honoring refresh — the default path for every read.
    async fn refresh_if_stale(&self) -> Result<()> {
        self.refresh(false).await
    }

    /// Report DB readability through the snapshot copy: state, total event
    /// count, and the age of the current snapshot.
    ///
    /// - `Absent`: the live file is missing.
    /// - `Readable`: the snapshot opened and the count SELECT succeeded.
    /// - `Unavailable`: the live file exists but the snapshot could not be
    ///   refreshed/queried.
    pub async fn health(&self) -> StoreHealth {
        if std::fs::metadata(&self.live_db_path).is_err() {
            // Clears any stale snapshot; never errors on an absent file.
            let _ = self.refresh_if_stale().await;
            return StoreHealth {
                db_state: DbState::Absent,
                event_count: None,
                snapshot_age_seconds: None,
            };
        }

        match self.count_events().await {
            Ok(count) => {
                let guard = self.inner.read().await;
                StoreHealth {
                    db_state: DbState::Readable,
                    event_count: Some(count),
                    snapshot_age_seconds: guard.as_ref().and_then(Snapshot::age_seconds),
                }
            }
            Err(e) => {
                warn!(error = %e, "trajectory db unreadable through snapshot copy");
                let guard = self.inner.read().await;
                StoreHealth {
                    db_state: DbState::Unavailable,
                    event_count: None,
                    snapshot_age_seconds: guard.as_ref().and_then(Snapshot::age_seconds),
                }
            }
        }
    }

    /// Total number of event rows. Absent live DB -> `Ok(0)`.
    pub async fn count_events(&self) -> Result<u64> {
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(0);
        };
        let mut rows = snapshot
            .conn
            .query("SELECT COUNT(*) FROM trajectory_events", ())
            .await
            .context("failed to count trajectory events")?;
        match rows.next().await {
            Ok(Some(row)) => {
                let count = row.get_value(0)?.as_integer().copied().unwrap_or(0);
                Ok(count as u64)
            }
            // A COUNT(*) row is always expected; Ok(None) is genuinely
            // "no row", not an error.
            Ok(None) => Ok(0),
            Err(e) => Err(e).context("failed to read event count row"),
        }
    }

    /// All events for a trajectory, ordered `timestamp ASC, id ASC` (the
    /// monotonic `id` tie-break is a deliberate improvement over the
    /// harness's timestamp-only ordering), deserialized into harness
    /// [`sondera_harness::Event`] structs. Absent live DB -> `Ok(vec![])`.
    pub async fn events_for_trajectory(
        &self,
        trajectory_id: &str,
    ) -> Result<Vec<sondera_harness::Event>> {
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(Vec::new());
        };

        // Column-explicit SELECT — never SELECT *: the column list IS the
        // schema contract pinned by tests/schema_contract.rs.
        let mut rows = snapshot
            .conn
            .query(
                r#"
            SELECT event_id, trajectory_id, agent_id, agent_provider,
                   timestamp, event_json, actor_id, actor_type,
                   correlation_id, causation_id, parent_id, raw_json
            FROM trajectory_events
            WHERE trajectory_id = ?1
            ORDER BY timestamp ASC, id ASC
            "#,
                [trajectory_id],
            )
            .await
            .context("failed to query trajectory events")?;

        // The snapshot is a non-atomic db+wal copy — it can OPEN
        // successfully yet error mid-statement (the open-time retry at
        // refresh does not cover this). Every iteration loop therefore
        // propagates Err explicitly: serving the partial result as Ok
        // produced truncated event lists, false 404s, Ok(0) health counts,
        // and Ok(0) poll cursors.
        let mut result = Vec::new();
        loop {
            match rows.next().await {
                Ok(Some(row)) => result.push(row_to_event(&row)?),
                Ok(None) => break,
                Err(e) => return Err(e).context("failed to iterate trajectory events"),
            }
        }
        // Counts only — never row contents (raw-hygiene discipline).
        debug!(count = result.len(), "read trajectory events");
        Ok(result)
    }

    /// Per-trajectory aggregates ordered newest-last-activity-first with
    /// keyset pagination: the cursor predicate lives in `HAVING` because the
    /// sort key is an aggregate, with a `trajectory_id` tie-break for
    /// trajectories sharing a last-activity timestamp.
    ///
    /// - `restrict_ids`: optional filter-phase output — `Some(&[])`
    ///   short-circuits to empty (never emit `IN ()`).
    /// - `before`: `(cursor_ts, cursor_id)` where `cursor_ts` is the stored
    ///   RFC 3339 `+00:00` TEXT form (callers re-render via chrono).
    /// - `limit`: already clamped by the route; always bound.
    ///
    /// SQL is assembled from FIXED clause fragments chosen by which options
    /// are present; placeholders are generated by count and ALL values are
    /// bound positionally — never interpolated.
    pub async fn trajectory_aggregates(
        &self,
        restrict_ids: Option<&[String]>,
        before: Option<(&str, &str)>,
        limit: u32,
    ) -> Result<Vec<AggregateRow>> {
        if restrict_ids.is_some_and(|ids| ids.is_empty()) {
            return Ok(Vec::new());
        }
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(Vec::new());
        };

        let mut params: Vec<turso::Value> = Vec::new();
        let mut sql = String::from(
            "SELECT trajectory_id, COUNT(*) AS event_count, \
             MIN(timestamp) AS first_event_at, \
             MAX(timestamp) AS last_activity, \
             MIN(agent_id) AS agent_id, \
             MIN(agent_provider) AS agent_provider, \
             SUM(CASE WHEN event_category = 'Action' THEN 1 ELSE 0 END) AS action_count, \
             SUM(CASE WHEN event_category = 'Observation' THEN 1 ELSE 0 END) AS observation_count, \
             SUM(CASE WHEN event_category = 'Control' THEN 1 ELSE 0 END) AS control_count, \
             SUM(CASE WHEN event_category = 'State' THEN 1 ELSE 0 END) AS state_count \
             FROM trajectory_events",
        );
        if let Some(ids) = restrict_ids {
            let placeholders = placeholder_list(params.len(), ids.len());
            sql.push_str(" WHERE trajectory_id IN (");
            sql.push_str(&placeholders);
            sql.push(')');
            params.extend(ids.iter().map(|id| turso::Value::Text(id.clone())));
        }
        sql.push_str(" GROUP BY trajectory_id");
        if let Some((cursor_ts, cursor_id)) = before {
            // The aggregate sort key is only addressable in HAVING.
            // cursor_ts is bound twice — distinct placeholders, same value.
            let p1 = params.len() + 1;
            let p2 = params.len() + 2;
            let p3 = params.len() + 3;
            sql.push_str(&format!(
                " HAVING (MAX(timestamp) < ?{p1} \
                 OR (MAX(timestamp) = ?{p2} AND trajectory_id < ?{p3}))"
            ));
            params.push(turso::Value::Text(cursor_ts.to_string()));
            params.push(turso::Value::Text(cursor_ts.to_string()));
            params.push(turso::Value::Text(cursor_id.to_string()));
        }
        let p_limit = params.len() + 1;
        sql.push_str(&format!(
            " ORDER BY last_activity DESC, trajectory_id DESC LIMIT ?{p_limit}"
        ));
        params.push(turso::Value::Integer(i64::from(limit)));

        let mut rows = snapshot
            .conn
            .query(&sql, params)
            .await
            .context("failed to query trajectory aggregates")?;

        let mut result = Vec::new();
        loop {
            match rows.next().await {
                Ok(Some(row)) => result.push(AggregateRow {
                    trajectory_id: text_at(&row, 0)?,
                    event_count: integer_at(&row, 1)?,
                    first_event_at: text_at(&row, 2)?,
                    last_activity: text_at(&row, 3)?,
                    agent_id: text_at(&row, 4)?,
                    agent_provider: text_at(&row, 5)?,
                    action_count: integer_at(&row, 6)?,
                    observation_count: integer_at(&row, 7)?,
                    control_count: integer_at(&row, 8)?,
                    state_count: integer_at(&row, 9)?,
                }),
                Ok(None) => break,
                Err(e) => return Err(e).context("failed to iterate trajectory aggregates"),
            }
        }
        debug!(count = result.len(), "read trajectory aggregates");
        Ok(result)
    }

    /// All Control-category rows for the given page of trajectory ids,
    /// ordered `timestamp ASC, id ASC` — the input to the status fold and
    /// the deny/escalate counts. Empty `ids` short-circuits (never emit
    /// `IN ()`).
    pub async fn control_rows(&self, ids: &[String]) -> Result<Vec<ControlRow>> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(Vec::new());
        };

        let placeholders = placeholder_list(0, ids.len());
        let sql = format!(
            "SELECT trajectory_id, event_type, event_json, actor_id \
             FROM trajectory_events \
             WHERE trajectory_id IN ({placeholders}) \
             AND event_category = 'Control' \
             ORDER BY timestamp ASC, id ASC"
        );
        let params: Vec<turso::Value> = ids
            .iter()
            .map(|id| turso::Value::Text(id.clone()))
            .collect();

        let mut rows = snapshot
            .conn
            .query(&sql, params)
            .await
            .context("failed to query control rows")?;

        let mut result = Vec::new();
        loop {
            match rows.next().await {
                Ok(Some(row)) => result.push(ControlRow {
                    trajectory_id: text_at(&row, 0)?,
                    event_type: text_at(&row, 1)?,
                    event_json: text_at(&row, 2)?,
                    actor_id: text_at(&row, 3)?,
                }),
                Ok(None) => break,
                Err(e) => return Err(e).context("failed to iterate control rows"),
            }
        }
        debug!(count = result.len(), "read control rows");
        Ok(result)
    }

    /// All Adjudicated rows, optionally time-bounded — the SQL prefilter
    /// feeding the Rust post-filter. `from`/`to` must be pre-rendered to the
    /// stored `to_rfc3339()` `+00:00` TEXT form by the caller so the TEXT
    /// comparison is chronologically sound.
    pub async fn adjudicated_rows(
        &self,
        from: Option<&str>,
        to: Option<&str>,
    ) -> Result<Vec<AdjudicatedRow>> {
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(Vec::new());
        };

        let mut params: Vec<turso::Value> = Vec::new();
        let mut sql = String::from(
            "SELECT trajectory_id, event_json, raw_json, actor_id \
             FROM trajectory_events \
             WHERE event_category = 'Control' AND event_type = 'Adjudicated'",
        );
        if let Some(from) = from {
            let p = params.len() + 1;
            sql.push_str(&format!(" AND timestamp >= ?{p}"));
            params.push(turso::Value::Text(from.to_string()));
        }
        if let Some(to) = to {
            let p = params.len() + 1;
            sql.push_str(&format!(" AND timestamp <= ?{p}"));
            params.push(turso::Value::Text(to.to_string()));
        }

        let mut rows = snapshot
            .conn
            .query(&sql, params)
            .await
            .context("failed to query adjudicated rows")?;

        let mut result = Vec::new();
        loop {
            match rows.next().await {
                Ok(Some(row)) => result.push(AdjudicatedRow {
                    trajectory_id: text_at(&row, 0)?,
                    event_json: text_at(&row, 1)?,
                    raw_json: optional_text_at(&row, 2)?,
                    actor_id: text_at(&row, 3)?,
                }),
                Ok(None) => break,
                Err(e) => return Err(e).context("failed to iterate adjudicated rows"),
            }
        }
        debug!(count = result.len(), "read adjudicated rows");
        Ok(result)
    }

    /// DISTINCT trajectory ids with any activity in the (optional) time
    /// window — the cheap prefilter when `from`/`to` are the ONLY filters.
    /// Bounds follow the same pre-rendered `+00:00` TEXT contract as
    /// [`Self::adjudicated_rows`].
    pub async fn trajectory_ids_in_range(
        &self,
        from: Option<&str>,
        to: Option<&str>,
    ) -> Result<Vec<String>> {
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(Vec::new());
        };

        let mut params: Vec<turso::Value> = Vec::new();
        let mut sql = String::from("SELECT DISTINCT trajectory_id FROM trajectory_events");
        let mut conjunction = " WHERE";
        if let Some(from) = from {
            let p = params.len() + 1;
            sql.push_str(&format!("{conjunction} timestamp >= ?{p}"));
            params.push(turso::Value::Text(from.to_string()));
            conjunction = " AND";
        }
        if let Some(to) = to {
            let p = params.len() + 1;
            sql.push_str(&format!("{conjunction} timestamp <= ?{p}"));
            params.push(turso::Value::Text(to.to_string()));
        }

        let mut rows = snapshot
            .conn
            .query(&sql, params)
            .await
            .context("failed to query trajectory ids in range")?;

        let mut result = Vec::new();
        loop {
            match rows.next().await {
                Ok(Some(row)) => result.push(text_at(&row, 0)?),
                Ok(None) => break,
                Err(e) => return Err(e).context("failed to iterate trajectory ids in range"),
            }
        }
        debug!(count = result.len(), "read trajectory ids in range");
        Ok(result)
    }

    /// Highest `trajectory_events.id` rowid visible through the snapshot —
    /// the poll fallback initializes its cursor here so a new dashboard
    /// process never replays history. Absent live DB -> `Ok(0)`.
    pub async fn max_event_row_id(&self) -> Result<i64> {
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(0);
        };
        let mut rows = snapshot
            .conn
            .query("SELECT COALESCE(MAX(id), 0) FROM trajectory_events", ())
            .await
            .context("failed to query max event row id")?;
        match rows.next().await {
            Ok(Some(row)) => Ok(row.get_value(0)?.as_integer().copied().unwrap_or(0)),
            // A COALESCE(MAX(id), 0) row is always expected; Ok(None) is
            // genuinely "no row", not an error.
            Ok(None) => Ok(0),
            Err(e) => Err(e).context("failed to read max event row id"),
        }
    }

    /// Events with `id > last`, ordered `id ASC`, each paired with its
    /// rowid — the poll fallback's id-cursor SELECT. The column list is the
    /// [`Self::events_for_trajectory`] contract with `id` appended LAST so
    /// the [`row_to_event`] indices (0-11) stay stable. The cursor is a
    /// server-internal i64, always bound. Absent live DB -> `Ok(vec![])`.
    pub async fn events_after_id(&self, last: i64) -> Result<Vec<(i64, sondera_harness::Event)>> {
        self.refresh_if_stale().await?;
        let guard = self.inner.read().await;
        let Some(snapshot) = guard.as_ref() else {
            return Ok(Vec::new());
        };

        let mut rows = snapshot
            .conn
            .query(
                r#"
            SELECT event_id, trajectory_id, agent_id, agent_provider,
                   timestamp, event_json, actor_id, actor_type,
                   correlation_id, causation_id, parent_id, raw_json, id
            FROM trajectory_events
            WHERE id > ?1
            ORDER BY id ASC
            "#,
                [turso::Value::Integer(last)],
            )
            .await
            .context("failed to query events after id")?;

        let mut result = Vec::new();
        loop {
            match rows.next().await {
                Ok(Some(row)) => {
                    let id = row.get_value(12)?.as_integer().copied().unwrap_or(0);
                    result.push((id, row_to_event(&row)?));
                }
                Ok(None) => break,
                Err(e) => return Err(e).context("failed to iterate events after id"),
            }
        }
        // Counts only — never row contents (raw-hygiene discipline).
        debug!(count = result.len(), "read events after id");
        Ok(result)
    }
}

/// Required text column at a positional index; NULL maps to "".
fn text_at(row: &turso::Row, idx: usize) -> Result<String> {
    Ok(row.get_value(idx)?.as_text().cloned().unwrap_or_default())
}

/// Non-negative integer column (COUNT/SUM output); NULL maps to 0.
fn integer_at(row: &turso::Row, idx: usize) -> Result<u64> {
    Ok(row
        .get_value(idx)?
        .as_integer()
        .copied()
        .unwrap_or(0)
        .max(0) as u64)
}

/// Optional text column: the harness inserts absent optionals as "" via
/// `unwrap_or("")`, so both NULL and "" mean `None`.
fn optional_text_at(row: &turso::Row, idx: usize) -> Result<Option<String>> {
    Ok(row
        .get_value(idx)?
        .as_text()
        .filter(|s| !s.is_empty())
        .cloned())
}

/// Map a `trajectory_events` row into a harness `Event`, replicating the
/// harness mapper semantics: lenient RFC 3339 parse with warn fallback,
/// actor_type matched on the Debug strings with `Agent` as the catch-all.
fn row_to_event(row: &turso::Row) -> Result<sondera_harness::Event> {
    let event_id = text_at(row, 0)?;
    let trajectory_id = text_at(row, 1)?;
    let agent_id = text_at(row, 2)?;
    let agent_provider = text_at(row, 3)?;
    let timestamp_str = text_at(row, 4)?;
    let event_json = text_at(row, 5)?;
    let actor_id = text_at(row, 6)?;
    let actor_type_str = text_at(row, 7)?;
    let correlation_id = text_at(row, 8)?;
    let causation_id = optional_text_at(row, 9)?;
    let parent_id = optional_text_at(row, 10)?;
    let raw_json = optional_text_at(row, 11)?;

    let timestamp = DateTime::parse_from_rfc3339(&timestamp_str)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(|e| {
            warn!(event_id = %event_id, error = %e, "failed to parse timestamp, using current time");
            Utc::now()
        });

    let event: sondera_harness::TrajectoryEvent =
        serde_json::from_str(&event_json).with_context(|| {
            format!("event_json no longer matches harness types (event {event_id})")
        })?;

    // Stored via the harness's Debug format; Agent is the catch-all.
    let actor_type = match actor_type_str.as_str() {
        "Human" => sondera_harness::ActorType::Human,
        "System" => sondera_harness::ActorType::System,
        "Policy" => sondera_harness::ActorType::Policy,
        _ => sondera_harness::ActorType::Agent,
    };

    let raw = raw_json.and_then(|s| serde_json::from_str(&s).ok());

    Ok(sondera_harness::Event {
        event_id,
        trajectory_id,
        agent: sondera_harness::Agent {
            id: agent_id,
            provider_id: agent_provider,
        },
        timestamp,
        event,
        actor: sondera_harness::Actor {
            id: actor_id,
            actor_type,
        },
        causality: sondera_harness::Causality {
            correlation_id,
            causation_id,
            parent_id,
        },
        raw,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Belt-and-suspenders proof: an INSERT through the store's own
    /// connection fails in query_only mode. turso enforces the pragma at
    /// statement-translation time BEFORE resolving the target table, so a
    /// freshly-initialized empty copy is a sufficient fixture — no
    /// write-capable store API is ever linked into src/.
    #[tokio::test]
    async fn query_only_rejects_writes() {
        let tmp = tempfile::tempdir().unwrap();
        let live = tmp.path().join("trajectories.db");
        // A zero-byte file is exactly what a fresh turso database file
        // looks like before its first commit; the copy opens as an empty
        // database.
        std::fs::File::create(&live).unwrap();

        let store = ReadOnlyStore::new(live, tmp.path().join("cache"));
        store.refresh_if_stale().await.unwrap();

        let guard = store.inner.read().await;
        let snapshot = guard
            .as_ref()
            .expect("snapshot must exist for a present live file");
        let err = snapshot
            .conn
            .execute("INSERT INTO trajectory_events (event_id) VALUES ('x')", ())
            .await
            .expect_err("INSERT through the store connection must fail");
        assert!(
            err.to_string().contains("query_only"),
            "error must name query_only mode, got: {err}"
        );
    }

    /// Lexicographic comparison of the stored RFC 3339 TEXT (`to_rfc3339()`,
    /// UTC `+00:00` form, variable subsecond precision) is chronologically
    /// order-consistent — the keyset cursor and the `from`/`to` predicates
    /// compare these strings directly in SQL.
    #[test]
    fn rfc3339_text_ordering() {
        use chrono::TimeZone;
        let base = Utc.with_ymd_and_hms(2026, 6, 1, 10, 0, 0).unwrap();
        // Zero, milli, and nano subsecond precision, straddling second
        // boundaries — the fractionless form must sort before any
        // fractional sibling of the same second ('+' < '.').
        let instants: Vec<DateTime<Utc>> = vec![
            base - chrono::Duration::nanoseconds(1),
            base,
            base + chrono::Duration::milliseconds(5),
            base + chrono::Duration::nanoseconds(123_456_789),
            base + chrono::Duration::milliseconds(500),
            base + chrono::Duration::seconds(1),
            base + chrono::Duration::seconds(1) + chrono::Duration::nanoseconds(7),
        ];

        let mut chronological = instants.clone();
        chronological.sort();
        let chronological_rendered: Vec<String> =
            chronological.iter().map(|dt| dt.to_rfc3339()).collect();

        let mut lexicographic: Vec<String> = instants.iter().map(|dt| dt.to_rfc3339()).collect();
        lexicographic.sort();

        assert_eq!(
            lexicographic, chronological_rendered,
            "lexicographic TEXT order must equal chronological order (A4)"
        );
    }

    /// Pointing the store at a nonexistent path serves empty and never
    /// creates the file (the default turso open mode would).
    #[tokio::test]
    async fn absent_db_never_created() {
        let tmp = tempfile::tempdir().unwrap();
        let live = tmp.path().join("nonexistent.db");
        let store = ReadOnlyStore::new(live.clone(), tmp.path().join("cache"));

        let events = store.events_for_trajectory("any").await.unwrap();
        assert!(events.is_empty());
        let health = store.health().await;
        assert_eq!(health.db_state, DbState::Absent);
        assert!(
            !live.exists(),
            "the store must never create the live DB (D-50)"
        );
    }
}
