//! Embeds the shipped Cedar baseline into the MCP server at compile time.
//!
//! The authoring tools serve the baseline so an agent can see what the engine
//! already forbids before drafting something that duplicates it. Embedding
//! rather than reading at runtime keeps the served corpus at exactly the
//! version of the binary serving it, which is the same reason the schema is
//! embedded in `lib.rs`.
//!
//! The table is generated by a std-only directory walk, so adding a `.cedar`
//! file to the baseline needs no edit here.

use std::path::{Path, PathBuf};
use std::{env, fs};

/// The shipped baseline, relative to this crate's manifest directory.
const BASELINE_DIR: &str = "../../.sondera/policies/cedar";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let baseline = PathBuf::from(BASELINE_DIR);
    println!("cargo:rerun-if-changed={}", baseline.display());

    if !baseline.is_dir() {
        // Without this the failure surfaces as a bare `NotFound` from
        // `read_dir` with no path attached, which is a long way from telling
        // someone the shipped baseline moved.
        return Err(format!(
            "the shipped Cedar baseline is missing: expected a directory at {} \
             (relative to crates/mcp/)",
            baseline.display()
        )
        .into());
    }

    let mut sources = Vec::new();
    collect(&baseline, &baseline, &mut sources)?;
    // Deterministic order: the generated table is compared byte-for-byte
    // across builds, and the served rows are ordered by it.
    sources.sort();

    let mut generated = String::from(
        "/// Every `.cedar` file of the shipped baseline as `(relative path, source)`.\n\
         pub(crate) const BASELINE_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (relative, path) in &sources {
        println!("cargo:rerun-if-changed={}", path.display());
        // `include_str!` rather than embedding the text here: the generated
        // file stays small, and a policy containing `"#` cannot break it.
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            relative,
            fs::canonicalize(path)?.display().to_string()
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR")?).join("baseline_generated.rs");
    fs::write(&out, generated)?;
    Ok(())
}

/// Collect `(path relative to `root`, full path)` for every `.cedar` file under
/// `dir`, recursing into subdirectories the way the harness's policy loader
/// does.
fn collect(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, PathBuf)>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect(root, &path, out)?;
        } else if path.extension().is_some_and(|ext| ext == "cedar") {
            let relative = path
                .strip_prefix(root)?
                .to_str()
                .ok_or("baseline policy path is not valid UTF-8")?
                // Forward slashes so the served ids are stable across
                // platforms; the walk is the only producer of these paths.
                .replace('\\', "/");
            out.push((relative, path));
        }
    }
    Ok(())
}
